### ISSUE TITLE
Can't get reload/injection to trigger

### ISSUE THREAD

**Issue by jessewallace** [BrowserSync/grunt-browser-sync#68]
Hey guys, just trying to get the live injection/refresh working, and it's to no avail.
My setup is a follows:

- running a grails app
- im forwarding our dev site ip to my ip (xxx.oursitehere.com), so all of our APIs will work
- i run the server and my grunt file is watching and compiling my sass w/ compass
- my gruntfile looks as so:
```js
module.exports = function(grunt) {

  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),

    watch: {
      css: {
        files: 'web-app/css/**/*.scss',
        tasks: ['compass']
      }
    },
   
    compass: {                  
      dist: {                   
        options: {              
          sassDir: 'web-app/css/',
          cssDir: 'web-app/css/',
          outputStyle: 'compressed'
        }
      }
    },

    browserSync: {
        bsFiles: {
            src : 'web-app/css/*.css'
        },
        options: {
            proxy: "xxx.oursitehere.com",
            watchTask: true
        }
    }

  });

  grunt.loadNpmTasks('grunt-contrib-sass');
  grunt.loadNpmTasks('grunt-contrib-compass');
  grunt.loadNpmTasks('grunt-contrib-watch');
  grunt.loadNpmTasks('grunt-browser-sync');

  grunt.registerTask('default', ['browserSync', 'watch']);

};
```
I get this when I run grunt:
```
Running "watch" task
Waiting...[BS] Proxying: http://ggdev.elasticbeanstalk.com
[BS] Now you can access your site through the following addresses:
[BS] Local: >>> http://localhost:3000
[BS] External: >>> http://192.168.0.59:3000
```

So, at this part I'm stuck, because I'll change a file, grunt sees, compiles and I get the BrowserSync command:

```
Done, without errors.
[BS] File Changed: site.css
[BS] Injecting file into all connected browsers...
Completed in 2.708s at Mon Aug 04 2014 00:44:02 GMT-0400 (Eastern Daylight Time) - Waiting...
```
But nothing is being injected.
I try at both the localhost:3000 and at xxx.oursitehere.com.  No dice on either.
Any idea of how I can get this working?

**Comment by billkeller** [comment]
I was encountering a similar issue where BrowserSync would see that a file had changed, but would not refresh the page. In my case, I had moved the <HTML> tag to an include file named header.html, so it was unable to inject the necessary script. After moving my opening <HTML> tag to index.html the problem was resolved. 

Thought I'd mention for anyone else who may find themselves in a similar scenario.

**Comment by blindfish3** [comment]
For info: I was having a similar issue (grunt-browser-sync 2.1.1) which I fixed quite simply using snippetOptions.

The rendered source of my page didn't include the browsersync script: so the script injection wasn't working.  Judging by this thread this was possibly because of issues with multiple conditional IE comments ahead of my `<html>` or possibly because I'm using Jade templates and includes...

If you are using template based pages it's a simple matter to inject a placeholder for the browsersync script and update snippetOptions to use this as a hook for the script injection.  For example the following injects the script after a comment I added to my test pages:

```javascript
snippetOptions: {
  rule : {
    match : /<!-- browsersync -->/,
    fn : function (snippet, match) {
      return match + snippet;
    }
  }
}
```
Alternatively you could update the rule to match a known element within the page and inject the script before/after that; though be careful to avoid injecting into existing tags ;)

**Comment by shakyShane** [comment]
thank @blindfish3

**Comment by shakyShane** [comment]
Also, http://www.browsersync.io/docs/options/#option-snippetOptions
