### ISSUE TITLE
HTTP and HTTPS

### ISSUE THREAD

**Issue by henriquea** [BrowserSync/grunt-browser-sync#69]
How can I serve both HTTP and HTTPS?

**Comment by shakyShane** [comment]
Sure! you make sure you're running the latest version

**Comment by aronrodrigues** [comment]
How??

**Comment by aronrodrigues** [comment]
browserSync({
			proxy: 'localhost:80'
})

I need to proxy 2 ports.

**Comment by shinnn** [comment]
http://www.browsersync.io/docs/options/#option-https

> Enable https for localhost development. **Note**: Proxy and Tunnel not currently supported.

**Comment by varemenos** [comment]
How exactly does this work?
Using `https: true` will start a server that serves only through `https` while not defining it (the https option) or setting it to false will serve only through `http`. Using grunt's multitasks to create a task for http and a task for https doesn't work either because it warns that a grunt instance is already running.

**Comment by harouny** [comment]
@shakyShane how can we configure http and https to run **at the same time**?

**Comment by weiyuan1993** [comment]
Write two different grunt task, one run with http and another run with https.
And then, use **two terminal** to run these two grunt task separately.
Now you can serve both HTTP and HTTPS, have fun~
